language: r
r:
  - devel
sudo: true
dist: xenial

before_install:
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev libproj-dev libgeos++-dev r-cran-rjava libv8-3.14-dev
  
after_success:
- Rscript -e 'covr::codecov()'

notifications:
    email:
      on_success: change
      on_failure: change
