language: r
sudo: true

before_install:
  - sudo apt-get install libproj-dev libgeos++-dev libgdal-dev

r_packages:
  - rgdal
  - roxygen2
  - rmarkdown

notifications:
    email:
      on_success: change
      on_failure: change
